version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
    volumes:
      - postgres.data:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq
    hostname: airflow.rabbitmq
    restart: always
    volumes:
        - rabbit.data:/var/lib/rabbitmq
  airflow.web:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - rabbit
     - postgres
    restart: always
    volumes:
      - airflow.logs:/opt/airflow/logs
      - airflow.plugins:/opt/airflow/plugins
      - ./dags:/opt/airflow/dags
    command: airflow webserver
  airflow.worker:
    build: .
    depends_on:
     - rabbit
     - postgres
    command: airflow worker
    restart: always
    volumes_from:
     - airflow.web
  airflow.scheduler:
    build: .
    depends_on:
     - rabbit
     - postgres
    command: airflow scheduler
    restart: always
    volumes_from:
     - airflow.web
  airflow.flower:
    build: .
    ports:
     - "5555:5555"
    depends_on:
     - rabbit
     - postgres
    command: airflow flower
    restart: always
    volumes_from:
     - airflow.web
volumes:
  rabbit.data:
    driver: local
  airflow.logs:
    driver: local
  airflow.plugins:
    driver: local
  postgres.data:
    driver: local
